### ISSUE TITLE
Could not extract file war3map.w3q

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#428]
Run as Wurst fails after logging "Could not extract file war3map.w3q".

Following that log is Error:

    de.peeeq.jmpq3.JMpqException: de.peeeq.jmpq3.JMpqException: File Not Found
        at de.peeeq.jmpq3.JMpqEditor.extractFile(JMpqEditor.java:220)
        at de.peeeq.wurstio.mpq.Jmpq3BasedEditor.extractFile(Jmpq3BasedEditor.java:47)
        at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.getDataStore(ProgramStateIO.java:106)
        at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.writeBack(ProgramStateIO.java:188)
        at de.peeeq.wurstscript.intermediateLang.interpreter.ILInterpreter.writebackGlobalState(ILInterpreter.java:172)
        at de.peeeq.wurstio.CompiletimeFunctionRunner.run(CompiletimeFunctionRunner.java:76)
        at de.peeeq.eclipsewurstplugin.console.WurstREPL.compileScript(WurstREPL.java:690)
        at de.peeeq.eclipsewurstplugin.console.WurstREPL.runMap(WurstREPL.java:455)
        at de.peeeq.eclipsewurstplugin.console.WurstConsole.launchMap(WurstConsole.java:96)
        at de.peeeq.eclipsewurstplugin.launch.LaunchDelegate.launchMap(LaunchDelegate.java:73)
        at de.peeeq.eclipsewurstplugin.launch.LaunchDelegate.launch(LaunchDelegate.java:40)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
        at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
        at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
        at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
    Caused by: de.peeeq.jmpq3.JMpqException: File Not Found
        at de.peeeq.jmpq3.HashTable.getBlockIndexOfFile(HashTable.java:79)
        at de.peeeq.jmpq3.JMpqEditor.extractFile(JMpqEditor.java:212)
        ... 15 more

Note that even unmodified versions of previously compilable maps fail. This is the latest build of wurstscript (clean build).

**Comment by peterzeller** [comment]
I think it can be ignored that this file is not found since it is optional in maps. Probably the problem/bug is somewhere else.

**Comment by peq** [comment]
I think it can be ignored that this file is not found since it is optional in maps. Probably the problem/bug is somewhere else.

**Comment by Cokemonkey11** [comment]
@peq Okay, maybe more info then. Normally after the compile succeeds, I launch the map and warcraft 3 crashes after loading.

This time, I just started eclipse and used "Run as Wurst", and I get this:

![image](https://cloud.githubusercontent.com/assets/1418966/12698213/f120da8a-c78e-11e5-9c0a-90e48b3d7322.png)

**Comment by peq** [comment]
Ok, this seems to be the real problem. Maybe @Crigges knows something about it, since it is a JMPQ problem.

**Comment by Crigges** [comment]
Thats the bug with the mapped byte buffer, under windows. I disabeld the workaround because it seemed to work for me without. I will redo the workaround and it should work well.

**Comment by Cokemonkey11** [comment]
Okay, cool, so I will just wait for patch. Thanks!

**Comment by Cokemonkey11** [comment]
@Crigges any progress?

**Comment by Crigges** [comment]
Fixed
