### ISSUE TITLE
Wurst WE opens Reign of Chaos world editor instead of Frozen Throne after 1.28a update

### ISSUE THREAD

**Issue by vitalexbel** [peq/WurstScript#527]
Do I need to change something in the settings?

**Comment by Frotty** [comment]
yes, update your wurstpack, as I've said in the other ticket.

**Comment by vitalexbel** [comment]
thanks
only this:
```
2017-06-17 17:25:28 INFO   >>> 17-06-2017 05:25:28 - Started compiler (1.7.0.0-jenkins-Wurst-330) with args --insertKeys
2017-06-17 17:25:28 INFO   compiler path1: file:/C:/Games/Wurst/Wurstpack/wurstscript/wurstscript.jar
2017-06-17 17:25:28 INFO   compiler path2: /C:/Games/Wurst/Wurstpack/
2017-06-17 17:25:28 SEVERE Error
java.lang.NullPointerException
	at de.peeeq.wurstio.Main.insertKeys(Main.java:179)
	at de.peeeq.wurstio.Main.main(Main.java:80)
```
When I open WurstWE, it creates worldedit121.exe file in War3 directory. And run RoC editor with Wurst functional. 
![screenshot_1](https://user-images.githubusercontent.com/29229748/27253738-b1a439a2-5382-11e7-989a-b55795ab71a0.png)
This is the Russian version.

**Comment by Frotty** [comment]
Hi, wurst cannot find the files it wants to inject or doesn't have permission.

Please verify the existance of the Wurstpack/wurstscript/font folder and 5 files in there.

Also run "WurstWe.exe" as administrator in case of missing rights.

**Comment by vitalexbel** [comment]
All 5 files are there. Even with administrator rights it still opens RoC.
I'll try to reinstall War3 today. Maybe this will help

**Comment by Frotty** [comment]
It won't, since this is a wurstscript issue. I tested this locally and now got the same problem. I think this only happens now since we are using gradle and the classloader location seems to have changed.

I have pushed a fix that loads the files correctly now. Please test and again post log.

**Comment by vitalexbel** [comment]
log:
```
2017-06-17 20:31:39 INFO   >>> 17-06-2017 08:31:39 - Started compiler (1.7.0.0-jenkins-Wurst-331) with args --insertKeys
2017-06-17 20:31:39 INFO   compiler path1: file:/C:/Games/Wurst/Wurstpack/wurstscript/wurstscript.jar
2017-06-17 20:31:39 INFO   compiler path2: /C:/Games/Wurst/Wurstpack/
2017-06-17 20:31:39 INFO   Wc3 Path: C:\Games\Warcraft III\
2017-06-17 20:32:31 INFO   inserted roc keys
2017-06-17 20:33:12 INFO   inserted tft keys
2017-06-17 20:33:12 INFO   Font insertion done.
```
2 dialogs:
![screenshot_2](https://user-images.githubusercontent.com/29229748/27254972-8fba2652-539c-11e7-8985-5b48b66ce726.png)
![screenshot_3](https://user-images.githubusercontent.com/29229748/27254973-8fbe2b08-539c-11e7-8d96-227883e6af7e.png)
right TfT editor:
![screenshot_4](https://user-images.githubusercontent.com/29229748/27254980-b2feafe8-539c-11e7-92bd-8a976cb105fc.png)
Everything works without errors.
Thanks for the rapid fix!

**Comment by Frotty** [comment]
👍
