### ISSUE TITLE
cant initialize workspace (wurstscript problem?)

### ISSUE THREAD

**Issue by vitalexbel** [peq/WurstScript#540]
This is the continuation of peq/wurst4vscode#23

problem still exists.

Wurst0 log:
```
2017-06-27 22:30:38 INFO   ### Started wurst version: (1.7.0.0-jenkins-Wurst-342)
2017-06-27 22:30:38 INFO   ### With wurst-args -languageServer
```

VScode console log when I open VScode:
```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Wurst extension activated!!
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Server started 10668!
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] setup file logging
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] stderr: Exception in thread "main" 
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] stderr: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] stderr: 
	at de.peeeq.wurstio.Main.main(Main.java:65)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] stderr: 

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] child process exited with code 1
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 This socket has been ended by the other party: Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:294:12)
    at Promise (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:225:39)
    at WurstServer.sendRequest (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:213:16)
    at WurstHoverProvider.provideHover (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\features\hoverProvider.js:8:32)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:352279
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57373
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:46346)
    at Object.d [as asWinJsPromise] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57336)
    at e.provideHover (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:352233)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:362450
e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
```

When I try to open a map using VScode, I get:
```
shell.ts:445 This socket has been ended by the other party: Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:294:12)
    at Promise (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:225:39)
    at WurstServer.sendRequest (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:213:16)
    at WurstServer.startMapIntern (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:268:55)
    at mapPromise.then.path (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:264:25)
    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:39252)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:42826)
    at n.Class.derive._oncancel._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:44654)
    at n.Class.derive._oncancel._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:44095)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57805
e.onUnexpectedError	@	shell.ts:445
(anonymous)	@	shell.ts:405
e.onUnexpectedError	@	errors.ts:68
o	@	errors.ts:88
(anonymous)	@	winjs.base.js:43
(anonymous)	@	winjs.base.js:38
winjs.base.js:45 WARNING: Promise with no error callback:69
winjs.base.js:46 
Object
error
:
Error: This socket has been ended by the other party at Socket.writeAfterFIN [as write] (net.js:294:12) at Promise (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:225:39) at WurstServer.sendRequest (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:213:16) at WurstServer.startMapIntern (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:268:55) at mapPromise.then.path (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:264:25) at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:39252) at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:42826) at n.Class.derive._oncancel._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:44654) at n.Class.derive._oncancel._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:44095) at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:57805
exception
:
null
handler
:
undefined
id
:
69
parent
:
undefined
promise
:
n.Class.derive._oncancel
__proto__
:
Object
```

when I try to clean wurst workspace, I get:
```
shell.ts:445 This socket has been ended by the other party: Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:294:12)
    at Promise (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:225:39)
    at WurstServer.sendRequest (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:213:16)
    at WurstServer.clean (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:230:61)
    at vscode.Disposable.from.vscode.commands.registerCommand (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\features\commands.js:5:169)
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:330741)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:312304)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:176531)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:177208)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
e.onUnexpectedError	@	shell.ts:445
(anonymous)	@	shell.ts:405
e.onUnexpectedError	@	errors.ts:68
o	@	errors.ts:88
(anonymous)	@	winjs.base.js:43
(anonymous)	@	winjs.base.js:38
winjs.base.js:45 WARNING: Promise with no error callback:71
winjs.base.js:46 
Object
error
:
Error: This socket has been ended by the other party at Socket.writeAfterFIN [as write] (net.js:294:12) at Promise (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:225:39) at WurstServer.sendRequest (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:213:16) at WurstServer.clean (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\WurstServer.js:230:61) at vscode.Disposable.from.vscode.commands.registerCommand (C:\Users\vital\.vscode\extensions\peterzeller.wurst-0.0.13\out\features\commands.js:5:169) at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:330741) at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:312304) at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:176531) at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:177208) at _combinedTickCallback (internal/process/next_tick.js:67:7)
exception
:
null
handler
:
undefined
id
:
71
parent
:
undefined
promise
:
n.Class.derive._oncancel
__proto__
:
Object
```

**Comment by vitalexbel** [comment]
I see that 343 version is building, so I will check it in 10 minutes. maybe problem disappears

**Comment by vitalexbel** [comment]
after 343 build now it **completely** works wothout any errors!
many thanks

**Comment by Frotty** [comment]
There is still a bug, that runmap can't be used because of access denied to WurstRunMap, but yeh, the other bug should be fixed.

**Comment by vitalexbel** [comment]
I ran the map without errors.

**Comment by Frotty** [comment]
good.
