### ISSUE TITLE
systems.crigges.jmpq3.JMpqException: File Not Found <war3map.w3u>.

### ISSUE THREAD

**Issue by vitalexbel** [peq/WurstScript#541]
I tested the map without any user created units in World Editor etc...
and got this
```
2017-07-01 22:48:58 INFO   running IS_COMPILETIME function points
2017-07-01 22:48:58 INFO   progress: Writing back generated objects
2017-07-01 22:48:58 INFO   Writing back UNITS
2017-07-01 22:48:58 INFO   Writing back filetype UNITS
2017-07-01 22:48:58 INFO   Error
systems.crigges.jmpq3.JMpqException: systems.crigges.jmpq3.JMpqException: File Not Found <war3map.w3u>.
	at systems.crigges.jmpq3.JMpqEditor.extractFileAsBytes(JMpqEditor.java:521)
	at de.peeeq.wurstio.mpq.Jmpq3BasedEditor.extractFile(Jmpq3BasedEditor.java:46)
	at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.writebackObjectFile(ProgramStateIO.java:238)
	at de.peeeq.wurstio.intermediateLang.interpreter.ProgramStateIO.writeBack(ProgramStateIO.java:184)
	at de.peeeq.wurstscript.intermediateLang.interpreter.ILInterpreter.writebackGlobalState(ILInterpreter.java:186)
	at de.peeeq.wurstio.CompiletimeFunctionRunner.run(CompiletimeFunctionRunner.java:73)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:266)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:95)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$32(LanguageWorker.java:242)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:218)
	at java.lang.Thread.run(Unknown Source)
Caused by: systems.crigges.jmpq3.JMpqException: File Not Found <war3map.w3u>.
	at systems.crigges.jmpq3.HashTable.getFileBlockIndex(HashTable.java:178)
	at systems.crigges.jmpq3.HashTable.getBlockIndexOfFile(HashTable.java:154)
	at systems.crigges.jmpq3.JMpqEditor.getMpqFile(JMpqEditor.java:583)
	at systems.crigges.jmpq3.JMpqEditor.extractFileAsBytes(JMpqEditor.java:518)
	... 10 more

2017-07-01 22:48:58 INFO   handleRequest fileChanged
2017-07-01 22:48:59 INFO   handleRequest fileChanged
```
then I created 1 custom unit in world editor, saved map and next time wurstscript run without problems
so I solved the problem by creating 1 unit in WE.
P.S.:
The same thing happened with other files. (.w3a,.w3b) I solved this the same way. created 1 custom ability etc
wurst_run.args file:
```
-runcompiletimefunctions
-injectobjects
```

**Comment by Frotty** [comment]
It was an old safety check which was no longer valid and shouldn't be needed anymore.
